# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ac2935fbbe99e21f26322e17074537d603974a1faadb9b3ee47f4c9c5d7a3b10500bcbc305cca1baedc6c0170981baded3655da298c3d8643a2c3bb71be4250

test:
  secret_key_base: 0b4d1848f4de1f29831caaf07cb544939035b1884675842a9a86c56a7007979d8e480fe01b5a7ca7aa1e16ca573d214565cd120201f0080e2bdf32fddb6d1760

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
